# PyTorch CUDA Test

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
device = torch.device("cuda")
x = torch.rand(10000, 10000, device=device)
y = x.to("cpu", torch.double)
print(x[0:5, 0:5])
print(y[0:5, 0:5])

tensor([[0.6684, 0.6918, 0.3228, 0.6555, 0.6795],
        [0.2302, 0.5329, 0.5622, 0.4000, 0.7667],
        [0.9127, 0.8541, 0.8870, 0.4095, 0.1043],
        [0.0250, 0.2224, 0.8410, 0.3443, 0.0731],
        [0.6962, 0.3126, 0.5870, 0.0209, 0.9542]], device='cuda:0')
tensor([[0.6684, 0.6918, 0.3228, 0.6555, 0.6795],
        [0.2302, 0.5329, 0.5622, 0.4000, 0.7667],
        [0.9127, 0.8541, 0.8870, 0.4095, 0.1043],
        [0.0250, 0.2224, 0.8410, 0.3443, 0.0731],
        [0.6962, 0.3126, 0.5870, 0.0209, 0.9542]], dtype=torch.float64)


# CPU Test

In [6]:
%%time
for i in range(0,100):
    ym = y * .5
    
print(ym[0:5, 0:5])

tensor([[0.3342, 0.3459, 0.1614, 0.3278, 0.3398],
        [0.1151, 0.2664, 0.2811, 0.2000, 0.3834],
        [0.4564, 0.4270, 0.4435, 0.2047, 0.0521],
        [0.0125, 0.1112, 0.4205, 0.1722, 0.0366],
        [0.3481, 0.1563, 0.2935, 0.0105, 0.4771]], dtype=torch.float64)
CPU times: user 32.9 s, sys: 27.1 s, total: 1min
Wall time: 11.1 s


# GPU Test

In [9]:
%%time
for i in range(0,100):
    xm = x * .5

print(xm[0:5, 0:5])

tensor([[0.3342, 0.3459, 0.1614, 0.3278, 0.3398],
        [0.1151, 0.2664, 0.2811, 0.2000, 0.3834],
        [0.4564, 0.4270, 0.4435, 0.2047, 0.0521],
        [0.0125, 0.1112, 0.4205, 0.1722, 0.0366],
        [0.3481, 0.1563, 0.2935, 0.0105, 0.4771]], device='cuda:0')
CPU times: user 401 ms, sys: 2.9 ms, total: 404 ms
Wall time: 404 ms


# Long Running GPU Test

In [10]:
%%time
for i in range(0,90000):
    xm = x * .5

print(xm[0:5, 0:5])

tensor([[0.3342, 0.3459, 0.1614, 0.3278, 0.3398],
        [0.1151, 0.2664, 0.2811, 0.2000, 0.3834],
        [0.4564, 0.4270, 0.4435, 0.2047, 0.0521],
        [0.0125, 0.1112, 0.4205, 0.1722, 0.0366],
        [0.3481, 0.1563, 0.2935, 0.0105, 0.4771]], device='cuda:0')
CPU times: user 3min 10s, sys: 2min 39s, total: 5min 50s
Wall time: 5min 51s
